<?php

namespace Oniti\Docga\ConnectorBundle\Filter\ProductValue;

use Oro\Bundle\FilterBundle\Form\Type\Filter\FilterType;
use Oro\Bundle\FilterBundle\Form\Type\Filter\TextFilterType;
use Oniti\Docga\ConnectorBundle\DataGrid\Form\Type\Filter\DocgaFilterType;
use Pim\Bundle\FilterBundle\Filter\ProductValue\StringFilter;
use Pim\Component\Catalog\Query\Filter\Operators;


class DocgaFilter extends StringFilter
{
    /** @var array */
    protected $operatorTypes = [
        TextFilterType::TYPE_CONTAINS     => Operators::CONTAINS,
        TextFilterType::TYPE_NOT_CONTAINS => Operators::DOES_NOT_CONTAIN,
        FilterType::TYPE_EMPTY            => Operators::IS_EMPTY,
        FilterType::TYPE_NOT_EMPTY        => Operators::IS_NOT_EMPTY,
    ];

    /**
     * {@inheritDoc}
     */
    protected function getFormType()
    {
        return TextCollectionFilterType::class;
    }

    public function getForm()
    {
        return parent::getForm(); // TODO: Change the autogenerated stub
    }
}
